export const NotificationType = {
  MATCH_INVITATION: "MATCH_INVITATION",
  MATCH_INVITATION_CANCELED: "MATCH_INVITATION_CANCELED",
  MATCH_STARTED: "MATCH_STARTED",
  MATCH_ENDED: "MATCH_ENDED",
  MATCH_COMPLETED: "MATCH_COMPLETED",
  SUBMISSION_RECEIVED: "SUBMISSION_RECEIVED",
  SUBMISSION_RESULT: "SUBMISSION_RESULT",
  OPPONENT_RESIGNED: "OPPONENT_RESIGNED",
  FRIEND_REQUEST_RECEIVED: "FRIEND_REQUEST_RECEIVED",
  FRIEND_REQUEST_ACCEPTED: "FRIEND_REQUEST_ACCEPTED",
  USER_RESIGNED: "USER_RESIGNED",
} as const;

export type NotificationType = typeof NotificationType[keyof typeof NotificationType];
