import { useState, useEffect, useRef } from 'react';
import { Camera, UserPlus, Upload } from 'lucide-react';
import { uploadProfileImage } from "../../services/UserService";
import {
    fetchFriendStatus,
    sendFriendRequest,
    acceptFriendRequest,
    rejectFriendRequest,
    removeFriend,
    type FriendStatus,
} from "../../services/FriendService";
import AppButton from '../common/AppButton';
import ConfirmationModal from '../common/ConfirmationModal';
import { generateInitialImage } from '../../utils/initialImageGenerator';
import { UserStatus } from '../../enums/UserStatus';
import { getStatusColor } from '../../utils/getUserStatusColor';
import { getStatusLabel } from '../../utils/getUserStatusLabel';

interface UserProfile {
    username: string;
    rank: string;
    currentRate: number;
    maxRate: number;
    friendCount: number;
    avatarUrl: string;
    userStatus: UserStatus;
}

interface ProfileHeaderProps {
    profile: UserProfile;
    setProfile: React.Dispatch<React.SetStateAction<UserProfile | null>>;
    isPrivate: boolean;
    color: string;
    onImageUpdated?: (newImageUrl: string) => void;
}

export default function ProfileHeader({
    profile,
    setProfile,
    isPrivate,
    color,
    onImageUpdated,
}: ProfileHeaderProps) {
    const [uploading, setUploading] = useState(false);
    const [error, setError] = useState<string | null>(null);
    const [preview, setPreview] = useState<string | null>(null);
    const [friendStatus, setFriendStatus] = useState<FriendStatus>("NONE");
    const [showConfirm, setShowConfirm] = useState(false);
    const autoGeneratedRef = useRef(false);


    const handleFileSelect = async (event: React.ChangeEvent<HTMLInputElement>) => {
        const file = event.target.files?.[0];
        if (!file) return;

        if (!file.type.startsWith('image/')) {
            setError('Please select an image file');
            setTimeout(() => setError(null), 3000);
            return;
        }

        if (file.size > 10 * 1024 * 1024) {
            setError('Image must be less than 10MB');
            setTimeout(() => setError(null), 3000);
            return;
        }

        setError(null);

        const reader = new FileReader();
        reader.onloadend = () => {
            setPreview(reader.result as string);
        };
        reader.readAsDataURL(file);

        await uploadImage(file);
    };

    const uploadImage = async (file: File) => {
        setUploading(true);
        setError(null);

        try {
            const response = await uploadProfileImage(file);
            setPreview(null);

            if (onImageUpdated) {
                onImageUpdated(response.imageUrl);
            }
        } catch (err) {
            setError(err instanceof Error ? err.message : 'Failed to upload image');
            setPreview(null);
            setTimeout(() => setError(null), 3000);
        } finally {
            setUploading(false);
        }
    };

     useEffect(() => {
    const autoGenerateAvatar = async () => {
        if (
            !isPrivate ||
            profile.avatarUrl ||
            preview ||
            uploading ||
            autoGeneratedRef.current
        ) {
            return;
        }

        autoGeneratedRef.current = true;

        try {
            const generatedFile = await generateInitialImage(profile.username, color);
            await uploadImage(generatedFile);
        } catch (err) {
            console.error("Failed to auto-generate avatar", err);
            autoGeneratedRef.current = false; // allow retry if it failed
        }
    };

    autoGenerateAvatar();
}, [isPrivate, profile.avatarUrl, profile.username, color]);



    useEffect(() => {
        const loadStatus = async () => {
            try {
                const status = await fetchFriendStatus(profile.username);
                setFriendStatus(status);
            } catch {
                setFriendStatus("NONE");
            }
        };
        loadStatus();
    }, [profile.username]);

    const handleAddFriend = async () => {
        try {
            await sendFriendRequest(profile.username);
            setFriendStatus("PENDING_SENT");
        } catch (err) {
            setError(err instanceof Error ? err.message : "Failed to send friend request");
            setTimeout(() => setError(null), 3000);
        }
    };

    const handleAcceptFriend = async () => {
        try {
            await acceptFriendRequest(profile.username);
            setFriendStatus("FRIENDS");
            setProfile(prev => prev ? { ...prev, friendCount: prev.friendCount + 1 } : prev);
        } catch (err) {
            setError(err instanceof Error ? err.message : "Failed to accept friend request");
            setTimeout(() => setError(null), 3000);
        }
    };

    const handleRejectFriend = async () => {
        try {
            await rejectFriendRequest(profile.username);
            setFriendStatus("NONE");
        } catch (err) {
            setError(err instanceof Error ? err.message : "Failed to reject friend request");
            setTimeout(() => setError(null), 3000);
        }
    };

    const handleUnFriend = async () => {
        try {
            await removeFriend(profile.username);
            setFriendStatus("NONE");
            setProfile(prev => prev ? { ...prev, friendCount: prev.friendCount - 1 } : prev);
            setShowConfirm(false);
        } catch (err) {
            setError(err instanceof Error ? err.message : "Failed to unFriend");
            setTimeout(() => setError(null), 3000);
        }
    };

    const handleCancelRequest = async () => {
        try {
            await removeFriend(profile.username);
            setFriendStatus("NONE");
        } catch (err) {
            setError(err instanceof Error ? err.message : "Failed to unFriend");
            setTimeout(() => setError(null), 3000);
        }
    };

    return (
        <div className="bg-container rounded-lg p-8 mb-8 relative">
            <div className="flex justify-between items-start">
                <div className="flex-1">
                    <div className="text-xl mb-2" style={{ color }}>{profile.rank}</div>
                    <h1 className="text-3xl font-bold mb-6" style={{ color }}>
                        {profile.username}
                    </h1>

                    <div className="space-y-2 text-text">
                        <div className="flex items-center gap-2">
                            <span className="text-xl text-text">Current Rate :</span>
                            <span className="text-2xl font-semibold" style={{ color }}>
                                {profile.currentRate}
                            </span>
                        </div>
                        <div className="flex items-center gap-2">
                            <span className="text-xl text-text">Max Rate :</span>
                            <span className="text-2xl font-semibold" style={{ color }}>
                                {profile.maxRate}
                            </span>
                        </div>
                        <div className="flex items-center gap-2">
                            <span className="text-xl text-text">Friend of :</span>
                            <span className="text-2xl font-semibold" style={{ color }}>
                                {profile.friendCount} users
                            </span>
                        </div>
                        <div className="flex items-center gap-2">
                            <span className="text-xl text-text">Status :</span>
                                <span className={`text-2xl font-semibold ${getStatusColor(profile.userStatus)}`}>
                                    {getStatusLabel(profile.userStatus)}
                                </span>
                        </div>
                    </div>
                </div>

                <div className="relative">
                    <div
                        className="w-80 h-80 rounded-full overflow-hidden border-4 relative"
                        style={{ borderColor: color }}
                    >
                  {preview || profile.avatarUrl ? (
                            <img
                                src={preview || profile.avatarUrl}
                                alt={profile.username}
                                className="w-full h-full object-cover"
                            />
                        ) : (
                            <div 
                                className="w-full h-full flex items-center justify-center select-none"
                                style={{ backgroundColor: `${color}20` }} // Light version of rank color
                            >
                                <span className="text-9xl font-bold uppercase" style={{ color }}>
                                    {profile.username.charAt(0)}
                                </span>
                            </div>
                        )}
                        {uploading && (
                            <div className="absolute inset-0 bg-black bg-opacity-60 flex items-center justify-center">
                                <div className="flex flex-col items-center gap-2">
                                    <Upload className="w-8 h-8 text-white animate-bounce" />
                                    <span className="text-white font-medium">Uploading...</span>
                                </div>
                            </div>
                        )}
                    </div>

                    {isPrivate ? (
                        <>
                            <input
                                type="file"
                                id="profile-image-input"
                                accept="image/*"
                                onChange={handleFileSelect}
                                className="hidden"
                                disabled={uploading}
                            />

                            <div className="absolute top-5 right-5 flex gap-2">
                                <label
                                    htmlFor="profile-image-input"
                                    className={`bg-background rounded-full p-3 hover:bg-gray-700 transition-colors ${uploading ? "opacity-50 cursor-not-allowed" : "cursor-pointer"
                                        }`}
                                    style={{ border: `3px solid ${color}` }}
                                    aria-label="Change profile image"
                                >
                                    <Camera className="w-8 h-8" style={{ color }} />
                                </label>
                            </div>
                        </>
                    ) : (
                        friendStatus === "NONE" && (
                            <button
                                onClick={handleAddFriend}
                                className="absolute top-5 right-5  bg-background rounded-full p-4 hover:bg-gray-700 transition-colors"
                                style={{ border: `3px solid ${color}` }}
                                aria-label="Add friend"
                            >
                                <UserPlus className="w-6 h-6" style={{ color }} />
                            </button>
                        )
                    )}

                    {error && (
                        <div className="absolute -bottom-10 left-0 right-0 bg-red-500 bg-opacity-90 text-white text-sm px-4 py-2 rounded text-center">
                            {error}
                        </div>
                    )}
                </div>
            </div>

            {!isPrivate && (
                <div className="absolute bottom-9 left-8">
                    {friendStatus === "PENDING_SENT" && (
                        <div className="flex gap-2">
                            <span
                                className="px-4 py-2 rounded-full text-lg uppercase font-medium"
                                style={{ border: `2px solid gold`, color: 'gold' }}
                            >
                                Request Pending
                            </span>
                            <AppButton
                                label="Cancel Request"
                                onClick={handleCancelRequest}
                                variant="negative"
                                size='large'
                            />
                        </div>
                    )}

                    {friendStatus === "FRIENDS" && (
                        <>
                        <div className="flex gap-2">
                            <span
                                className="px-4 py-2 rounded-full text-lg uppercase font-medium"
                                style={{ border: `2px solid  #34D399`, color: '#34D399' }}
                            >
                                Friends
                            </span>
                            <AppButton
                                label="Unfriend"
                                onClick={() => setShowConfirm(true)}
                                variant="negative"
                                size='large'
                            />
                        </div>
                        <ConfirmationModal isOpen={showConfirm} onClose={() => setShowConfirm(false)}
                            onConfirm={handleUnFriend}
                            title="Confirm Unfriend"
                            message={`Are you sure you want to unfriend ${profile.username}?`}
                            confirmText="Unfriend"
                            cancelText="Cancel"
                        />
                        </>
                    )}

                    {friendStatus === "PENDING_RECEIVED" && (
                        <div className="flex gap-2">
                            <AppButton
                                label="Accept"
                                onClick={handleAcceptFriend}
                                variant="positive"
                                size='large'
                            />
                            <AppButton
                                label="Reject"
                                onClick={handleRejectFriend}
                                variant="negative"
                                size='large'
                            />
                        </div>
                    )}
                </div>
            )}
        </div>
    );

}